/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#b5d4ff",
        "on-primary": "#ffffff",
        "background": "#f8f9ff",
        "surface-variant": "#d3e4fe",
        "surface": "#f8f9ff",
        "on-surface": "#0b1c30",
        "on-tertiary-container": "#bcd3fc",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#d5e3ff",
        "on-secondary-fixed-variant": "#005049",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#e5eeff",
        "on-surface-variant": "#414750",
        "surface-container-highest": "#d3e4fe",
        "outline": "#727781",
        "surface-bright": "#f8f9ff",
        "on-secondary-container": "#006f66",
        "on-background": "#0b1c30",
        "primary-fixed-dim": "#a1c9ff",
        "surface-container-high": "#dce9ff",
        "on-tertiary-fixed": "#001c3b",
        "surface-tint": "#1660a3",
        "inverse-primary": "#a1c9ff",
        "tertiary-container": "#455b7e",
        "on-primary-fixed-variant": "#004880",
        "on-tertiary-fixed-variant": "#314769",
        "primary": "#004479",
        "inverse-on-surface": "#eaf1ff",
        "error-container": "#ffdad6",
        "secondary-container": "#86f2e4",
        "tertiary-fixed-dim": "#b1c7f0",
        "primary-fixed": "#d2e4ff",
        "surface-dim": "#cbdbf5",
        "surface-container-low": "#eff4ff",
        "on-secondary": "#ffffff",
        "secondary": "#006a61",
        "primary-container": "#0b5c9e",
        "outline-variant": "#c1c7d2",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#89f5e7",
        "secondary-fixed-dim": "#6bd8cb",
        "on-secondary-fixed": "#00201d",
        "on-primary-fixed": "#001c37",
        "on-error": "#ffffff",
        "tertiary": "#2d4365",
        "inverse-surface": "#213145",
        "error": "#ba1a1a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "margin-lg": "3rem",
        "space-sm": "0.5rem",
        "gutter-lg": "2rem",
        "margin-md": "2rem",
        "gutter": "1rem",
        "space-xl": "2.5rem",
        "margin": "1rem",
        "space-lg": "1.5rem",
        "space-md": "1rem",
        "gutter-md": "1.5rem"
      },
      fontFamily: {
        "sans": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "label-md": ["0.8125rem", { "lineHeight": "1.125rem", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "headline-sm": ["1.125rem", { "lineHeight": "1.5rem", "fontWeight": "600" }],
        "body-sm": ["0.875rem", { "lineHeight": "1.25rem", "fontWeight": "400" }],
        "headline-lg-mobile": ["1.375rem", { "lineHeight": "1.875rem", "letterSpacing": "0", "fontWeight": "600" }],
        "label-sm": ["0.6875rem", { "lineHeight": "1rem", "letterSpacing": "0.04em", "fontWeight": "700" }],
        "label-lg": ["0.9375rem", { "lineHeight": "1.25rem", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "body-lg": ["1.125rem", { "lineHeight": "1.75rem", "fontWeight": "400" }],
        "headline-lg": ["1.75rem", { "lineHeight": "2.25rem", "letterSpacing": "-0.015em", "fontWeight": "700" }],
        "body-md": ["1rem", { "lineHeight": "1.5rem", "fontWeight": "400" }],
        "headline-xl-mobile": ["1.75rem", { "lineHeight": "2.25rem", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-xl": ["2.25rem", { "lineHeight": "2.75rem", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["1.25rem", { "lineHeight": "1.75rem", "fontWeight": "600" }]
      },
      boxShadow: {
        "silky-xs": "0 1px 3px 0 rgba(15, 23, 42, 0.03), 0 1px 2px -1px rgba(15, 23, 42, 0.02)",
        "silky-sm": "0 2px 8px -1px rgba(15, 23, 42, 0.04), 0 1px 4px -1px rgba(15, 23, 42, 0.02)",
        "silky": "0 4px 20px -2px rgba(15, 23, 42, 0.04), 0 2px 6px -1px rgba(15, 23, 42, 0.02)",
        "silky-md": "0 10px 25px -3px rgba(15, 23, 42, 0.05), 0 4px 10px -2px rgba(15, 23, 42, 0.025)",
        "silky-lg": "0 16px 36px -4px rgba(15, 23, 42, 0.07), 0 6px 14px -3px rgba(15, 23, 42, 0.03)",
        "silky-xl": "0 24px 48px -8px rgba(15, 23, 42, 0.09), 0 8px 20px -4px rgba(15, 23, 42, 0.035)",
        "silky-hover": "0 20px 38px -6px rgba(15, 23, 42, 0.09), 0 8px 16px -3px rgba(15, 23, 42, 0.04)"
      }
    }
  },
  plugins: [],
}
